### ISSUE TITLE
Nonsensical results for identical videos with certain sizes

### ISSUE THREAD

**Issue by 0xb01u** [fraunhoferhhi/xpsnr#5]
## Description of the issue

When using the same video (file) both as reference and reconstructed videos for the filter, the XPSNR filter outputs results for each frame that do not make sense, including negative values. This seems to happen for specific video sizes; for example 854x480 (480p 16:9), 426x240 (240p 16:9), or 480x360 (360p 4:3).

## Expected behavior

Since the reference and reconstructed videos are the very same, the XPSNR filter should output "infinite" as the result for each component on every frame (there is no noise in the reconstructed signal).

## Steps to reproduce

1. Obtain a 240p 16:9 video file, `video`
2. Execute the FFmpeg XPSNR filter using `video` both as reference and reconstructed videos
3. Let the process finish and check the results

## Example

This issue has been noted on the following YouTube video: https://youtu.be/FtutLA63Cp8.

The video is downloaded using [yt-dlp](https://github.com/yt-dlp/yt-dlp):
```
yt-dlp https://youtu.be/watch?v=FtutLA63Cp8
```
By default, yt-dlp downloads the highest available video size, which in this case corresponds to 480x360.

The downloaded video is renamed to `BadApple.webm` for convenience.

The XPSNR filter is executed using the following command:
```
ffmpeg -i BadApple.webm -i BadApple.webm -lavfi xpsnr="stats_file=bad_apple_xpsnr.log" -f null -
```
And the results output by the filter are the following:
```
XPSNR  Y: -6.2378  U: 4.2878  V: 4.2878  (minimum: -6.2378)
```

The issue has also been noted on other (YouTube) videos. For example [this one](https://youtu.be/5qjnDd1rsII), when downloading the 480p or 240p versions (`yt-dlp -f 397 https://youtu.be/5qjnDd1rsII` and `yt-dlp -f 395 https://youtu.be/5qjnDd1rsII`, respectively).
For all the videos with an aspect ratio of 16:9 tested, it is always noted for the 480p and 240p resolutions, but not for the other ones (namely 1080p, 720p, and 360p).

**Comment by crhelmrich** [comment]
Hi and thanks very much for this thorough report! A colleague of mine identified the problem.

Could you please try the latest commit (023f4dd0) on top of the recent *FFmpeg 7.0* release?

Thanks and best,

Christian

**Comment by 0xb01u** [comment]
Hi!

Thank you for taking a look at this issue, as well as for updating the filter to a recent version of FFmpeg.

I have now re-tested my example videos and I can confirm the updated filter produces the expected results.

So this seems to be fixed now :)
